# Generated by Django 4.0.4 on 2023-04-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='sony', max_length=40),
            preserve_default=False,
        ),
    ]
