# Generated by Django 4.0.4 on 2023-04-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
    ]
