# Generated by Django 4.1.5 on 2023-05-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=40)),
                ('envio', models.CharField(max_length=40)),
            ],
        ),
    ]
