# Generated by Django 4.2 on 2023-05-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebasEs',
            fields=[
                ('user', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('nombreEs', models.CharField(default='', max_length=50)),
                ('apellidoEs', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(default=0, max_length=10)),
                ('codigoPostal', models.IntegerField(default=0)),
                ('rut', models.CharField(default=0, max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
