# Generated by Django 4.2 on 2023-05-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_historial_cantidad_remove_historial_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='envio',
            new_name='estadoEnvio',
        ),
        migrations.RenameField(
            model_name='historial',
            old_name='estado',
            new_name='estadoPago',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='precio',
        ),
    ]
