# Generated by Django 4.2 on 2023-05-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_envio_historial_estadoenvio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='estadoEnvio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historial',
            name='estadoPago',
            field=models.BooleanField(default=False),
        ),
    ]
