# Generated by Django 4.2 on 2023-05-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_historial_estadoenvio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='tipoPago',
            field=models.BooleanField(choices=[(True, 'Transferencia'), (False, 'Transbank')], default=False),
        ),
    ]
