# Generated by Django 4.2 on 2023-05-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_historial_tipopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigoPostal',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='', max_length=10),
        ),
    ]
