# Generated by Django 4.1.5 on 2023-05-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_usuario_groups_remove_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioInvitado',
            fields=[
                ('nombre', models.CharField(max_length=16)),
                ('apellido', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('rut', models.CharField(default='', max_length=10)),
                ('direccion', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(default=0, max_length=10)),
                ('codigoPostal', models.IntegerField(default=0, max_length=50)),
                ('estado', models.CharField(default='', max_length=50)),
                ('ciudad', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
