# Generated by Django 4.1.5 on 2023-05-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_usuarioinvitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='historial',
            name='tipoUsuario',
            field=models.BooleanField(choices=[(True, 'Logueado'), (False, 'Invitado')], default=False),
        ),
    ]
