# Generated by Django 4.1.3 on 2023-05-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_historial_email_historial_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cam_auto',
            field=models.IntegerField(default=1),
        ),
    ]
