# Generated by Django 4.1.3 on 2023-05-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_usuario_cam_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHistorial', models.IntegerField()),
                ('idProducto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
