# Generated by Django 4.2 on 2023-05-16 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tipoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='idTipoProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoproducto'),
        ),
    ]
