# Generated by Django 4.2.1 on 2023-05-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_producto_idtipoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='estadoStock',
            field=models.BooleanField(default=False),
        ),
    ]
