# Generated by Django 4.2.1 on 2023-05-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_historial_estadostock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='estadoStock',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='estadoStock',
            field=models.BooleanField(default=False),
        ),
    ]
