# Generated by Django 4.2.1 on 2023-05-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='estadoStock',
            field=models.IntegerField(default=0),
        ),
    ]
